### ISSUE TITLE
[BUG] Endless Activity Indicator on Paywall

### ISSUE THREAD

**Issue by michaeljajou** [superwall-me/paywall-ios#78]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `Paywall` version: 2.5.2
- iOS version(s): 16.0
- CocoaPods/Carthage version (if applicable):
- Xcode version: 14.0
- Devices/Simulators affected: iPhone 12 Pro Max

### Describe the bug
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue.

**RevenueCat Enabled Project**
If within the same app session, a user makes a purchase, then switches to a different account (one that RevenueCat does not have marked as having an active subscription) and attempts to make a purchase (or at least restoring purchases in order to transfer the subscription to that account), then the Paywall will show an endless activity indicator.

While this is an edge case, here is a common example where this can be an issue:
1. A user purchases a subscription before creating an account
2. After purchasing the subscription, they create their account
3. The user realizes they made an account with the wrong email, and would like to make a new account with a different email
4. They create their new account, and they go to the Paywall again to transfer the subscription to that new account
5. The paywall presents an endless activity indicator giving the user a stressful experience. 

### Steps to reproduce
Please also include a description of expected vs. actual behaviour
1. Start a new App Session and initialize Paywall without a user id
2. Trigger a paywall and make a purchase (must be a purchase cannot be a restore)
3. After a successful purchase, (log in/sign up, whatever is necessary to call `Paywall.identify()`)
4. Trigger a paywall again, and an endless activity indicator will appear, which essentially locks the UI preventing the user from dismissing the view.

### Other Information
I have a video recording of this issue - yet it previews some sensitive data of mine, I'd be happy to email it, I just don't want to post it on the web

**Comment by yusuftor** [comment]
In your use case, you'd need to call `Paywall.reset()` when you reach step 3 - when the user realises they need to make a new account they'd log out. At that point, you'd call `Paywall.reset()`. This resets the data stored for the user back to anonymous - and incidentally also clears that spinner on the paywall. Once someone's purchased a product they shouldn't be shown the paywall again for the same user because `isUserSubscribed()` should be `true`.

**Comment by michaeljajou** [comment]
Gotcha, so anytime an anonymous user makes a purchase, and I require them to create an account

I should call Paywall.reset() in between creating the account and making the subscription?

**Comment by yusuftor** [comment]
Wait, it should be like this:

1. A user purchases a subscription before creating an account
2. After purchasing the subscription, they create their account **(Call `Paywall.identify(userId: userId)`)**
3. The user realizes they made an account with the wrong email, and would like to make a new account with a different email **(Call `Paywall.reset()` when they log out here)**
4. They create their new account, **(Call `Paywall.identify(userId: newUserId)`)** and they go to the Paywall again to transfer the subscription to that new account

Does that make sense?

In v3 we're going to have specific `logout()`, `logIn(userId:)` and `createAccount(userId:)` functions so that it's easier to understand what to call when :)

**Comment by yusuftor** [comment]
You should still be able to tell the difference between a new account and an existing account on your side though right? The reason we need to separate this is because we retrieve the paywall assignments from our servers. For login, we have to wait for assignments before firing triggers whereas if you're creating an account for the first time we don't have to wait. Otherwise a user could end up with the wrong paywall.

**Comment by michaeljajou** [comment]
Not without adding some extra logic on our part, this would be the first case where our client app would need to differentiate between a sign up/login as the other services we use 

Mixpanel
Revenuecat
OneSignal 

All have the same methods for identifying users regardless of new accounts vs existing accounts. 

Either way if it needs to be done we'll get it done

**Comment by yusuftor** [comment]
Okay, well the current SDK doesn't wait for paywall assignments on login so you *could* keep it the same if you've had no issues. Problems may arise if you immediately fire a trigger after login as there'll be a race condition. But we're looking to make it more explicit and I'd recommend implementing that when it's out. I'm going to close this issue now but if you still have issues feel free to reopen it.

**Comment by dimpy-iroid** [comment]
I have the same setup in my app as above. I have to display the paywall on the tabbar's first screen. I have shown like below:

```
//superwall delegate
            Superwall.shared.delegate = self
            
            //show paywall
            Superwall.shared.register(event: SuperwallEvents.CAMPAIGN_TRIGGER.rawValue) {
                print("Action to take if they are on a paid plan")
            }
```

Below is the delegate:

```
// MARK: - Superwall Delegate
extension InputCameraScreen: SuperwallDelegate {
    func handleSuperwallEvent(withInfo eventInfo: SuperwallEventInfo) {
        switch eventInfo.event {
        case .transactionComplete(let transaction, let product, let paywallInfo):
            print("Converted from paywall originalTransactionIdentifier: \(transaction?.originalTransactionIdentifier ?? "")")
            print("Converted from paywall storeTransactionId: \(transaction?.storeTransactionId ?? "")")
            print("Converted from paywall productIdentifier: \(product.productIdentifier)")
            print("Converted from paywall paywallInfo: \(paywallInfo.identifier)")
        case .transactionRestore(let restoreType, let paywallInfo):
            print("transactionRestore restoreType \(restoreType)")
        default:
            print("default \(#function) - \(eventInfo.event)")
        }
    }
}
```

till now, the user has not created any account yet, and if a user subscribes to any of our plans, then transactionComplete will get called. I'm not sure how I send "receipt_data" and "transaction_id" to the backend when the transaction is completed successfully. Also, without userID, how can I send "receipt_data" and "transaction_id" to the backend?

and after that, if the user creates an account, I'm calling this method: 
```
// save userId in Superwall
        if let userId = loginData.userId {
            Superwall.shared.identify(userId: userId)
        }
```

and when they logout:
`Superwall.shared.reset()`

So, How do I attach the purchase with the user's account?
as mentioned above, They create their new account, (Call Paywall.identify(userId: newUserId)) and they go to the Paywall again to transfer the subscription to that new account.

How do I do this? I mean how will user transfer the subscription to that new account?
Am I missing something? Please guide me as this is my first time implementing subscriptions in my app.
